site_name: doi_downloader
theme: readthedocs
nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Examples: examples.md
  - Developing new plugins: writing_a_plugin.md
  - Contributing: contributing.md
  - License: license.md
